gamesearch/urls.py
from django.conf.urls import url
from . import views

app_name = 'gamesearch'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<game_id>[0-9]+)/$', views.game, name='game'),
    url(r'^action/$', views.topgames, name='topgames'),
]

webgame/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from homepage import views

urlpatterns = [
    url(r'^$', views.index),
    url(r'^search/', include('gamesearch.urls')),
    url(r'^admin/', admin.site.urls),
]

gamesearch/models.py
from __future__ import unicode_literals

from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator


class Genre(models.Model):
    """A genre's information, including which game has this genre."""

    api_id = models.IntegerField(primary_key=True)
    name = models.TextField()


class Game(models.Model):
    """A game's information."""

    api_id = models.IntegerField(primary_key=True)
    name = models.TextField()
    summary = models.TextField()
    description = models.TextField()
    score = models.FloatField(default=0)
    n_reviews = models.IntegerField(default=0)
    cover_img = models.URLField()
    genres = models.ManyToManyField(Genre)

    def add_score(self, score):
        """Update the average score of this game."""

        if score <= 5.0:
            self.score = self.score * self.n_reviews + score
            self.n_reviews += 1
            self.score /= self.n_reviews

homepage/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

gamesearch/views.py
from django.shortcuts import render
from django.core.cache import cache

from .models import Game, Genre
from utils import GBSearcher

import os
import sys


def index(request):

    params = {}

    if request.method == "POST":
        # request data
        game_name = request.POST.get('game')

        cache_key = '_'.join(game_name.split())
        games = cache.get(cache_key)

        if games is None:
            print "request data on server"
            sys.stdout.flush()

            user_agent = request.META['HTTP_USER_AGENT']
            games = GBSearcher.search_by_name(game_name, user_agent)

            # cache the search results to reduce number of api requests
            cache.set(cache_key, games)

        params = {'games': games}

    return render(request, 'gamesearch/index.html', params)


def game(request, game_id):

    game, created = Game.objects.get_or_create(api_id=game_id)

    # if this game is not in the database
    if created:
        print "request data on server"

        user_agent = request.META['HTTP_USER_AGENT']
        game_info = GBSearcher.search_by_id(game_id, user_agent)

        game.name = game_info['name']
        game.summary = game_info['deck']
        game.cover_img = game_info['image']['super_url']
        game.description = game_info['description']
        game.save()

        # extract game's genres
        get_info = lambda x: (x['id'], x['name'])
        genres = map(get_info, game_info['genres'])

        for gen in genres:
            gen_id, gen_name = gen
            new_gen = Genre(api_id=gen_id, name=gen_name)
            new_gen.save()
            game.genres.add(new_gen)

        game.save()

    # concatenate all genres as a single string
    genres = ', '.join(map( lambda x: x.name, game.genres.all() ))

    return render(request, 'gamesearch/game.html', {'game': game, 'genres': genres})


def topgames(request):
    user_agent = request.META['HTTP_USER_AGENT']
    # game = GBSearcher.search_by_id(game_id, user_agent)

    # concatenate game's genres and platforms
    # get_name = lambda x: x['name']
    # game['genres'] = ', '.join(map(get_name, game['genres']))
    # game['platforms'] = ', '.join(map(get_name, game['platforms']))
    return render(request, 'gamesearch/topgames.html', {})

homepage/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'homepage/index.html')

gamesearch/templates/gamesearch/base.html
{% load staticfiles %}
{% load search_extras %}
<!DOCTYPE html>
<html lang="en">

<head>
<meta charset="utf-8">
<meta name="robots" content="all,follow">
<meta name="googlebot" content="index,follow,snippet,archive">
<meta name="viewport" content="width=device-width, initial-scale=1">

<title>Home Page</title>

<meta name="keywords" content="">

<link href='https://fonts.googleapis.com/css?family=Roboto:400,100,100italic,300,300italic,500,700,800' rel='stylesheet' type='text/css'>

<!-- Bootstrap and Font Awesome css -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">

<!-- Css animations  -->
<link href="{% static 'animate.css/animate.min.css' %}" rel="stylesheet">

<!-- Theme stylesheet, if possible do not edit this stylesheet -->
<link href="{% static 'gamesearch/css/style.default.css' %}" rel="stylesheet" id="theme-stylesheet">

<!-- Responsivity for older IE -->
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->

<!-- owl carousel css -->

<link href="{% static 'owl.carousel/dist/assets/owl.carousel.css' %}" rel="stylesheet">
<link href="{% static 'owl.carousel/dist/assets/owl.theme.default.css' %}" rel="stylesheet">

<!-- Custom stylesheet - for your changes -->
<link href="{% static 'gamesearch/css/custom.css' %}" rel="stylesheet">
</head>

<body>

<div id="all">

	<header>

	<!-- *** TOP ***
		_________________________________________________________ -->
	<div id="top">
		<div class="container">
			<div class="row">
				<div class="col-xs-5 contact">
					<form action="/search/" method="post">
						{% csrf_token %}
						<div class="input-group">
							<input type="text" class="form-control" name="game" placeholder="Type the name of your game">
							<span class="input-group-btn">
								<button class="btn btn-default" type="submit">
									<i class="fa fa-search"></i>
								</button>
							</span>
						</div>
					</form>                  
				</div>
				<div class="col-xs-7">                        
					<div class="login">
						<a href="#" data-toggle="modal" data-target="#login-modal"><i class="fa fa-sign-in"></i> <span class="hidden-xs text-uppercase">Sign in</span></a>
						<a href="customer-register.html"><i class="fa fa-user"></i> <span class="hidden-xs text-uppercase">Sign up</span></a>
					</div>

				</div>
			</div>
		</div>
	</div>

	<!-- *** TOP END *** -->

	<!-- *** NAVBAR ***
_________________________________________________________ -->

	<div class="navbar-affixed-top" data-spy="affix" data-offset-top="200">

		<div class="navbar navbar-default yamm" role="navigation" id="navbar">

			<div class="container">
				<div class="navbar-header">
					<div class="navbar-buttons">
						<button type="button" class="navbar-toggle btn-template-main" data-toggle="collapse" data-target="#navigation">
							<span class="sr-only">Toggle navigation</span>
							<i class="fa fa-align-justify"></i>
						</button>
					</div>
				</div>
				<!--/.navbar-header -->

				<div class="navbar-collapse collapse" id="navigation">

					<ul class="nav navbar-nav navbar-right">
						<li class="dropdown active">
							<a href="javascript: void(0)" class="dropdown-toggle" data-toggle="dropdown">Home <b class="caret"></b></a>
							<!-- <ul class="dropdown-menu">
								<li><a href="index.html">Option 1: Default Page</a>
								</li>
								<li><a href="index2.html">Option 2: Application</a>
								</li>
								<li><a href="index3.html">Option 3: Startup</a>
								</li>
								<li><a href="index4.html">Option 4: Agency</a>
								</li>
								<li><a href="index5.html">Option 5: Portfolio</a>
								</li>
							</ul> -->
						</li>
						<li class="dropdown use-yamm yamm-fw">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">Top PC Games<b class="caret"></b></a>
							<ul class="dropdown-menu">
								<li>
									<div class="yamm-content">
										<div class="row">
											<div class="col-sm-3">
												<ul>
													<li><a href="/search/action">Action</a>
													</li>
													<li><a href="/search/adventure">Adventure</a>
													</li>
													<li><a href="/search/arcade">Arcade</a>
													</li>
													<li><a href="/search/board">Board</a>
													</li>
												</ul>
											</div>
											<div class="col-sm-3">
												<ul>
													<li><a href="/search/card">Card</a>
													</li>
													<li><a href="/search/casino">Casino</a>
													</li>
													<li><a href="/search/family">Family</a>
													</li>
													<li><a href="/search/music">Music</a>
													</li>
												</ul>
											</div>
											<div class="col-sm-3">
												<ul>
													<li><a href="/search/puzzle">Puzzle</a>
													</li>
													<li><a href="/search/racing">Racing</a>
													</li>
													<li><a href="/search/rpg">RPG</a>
													</li>
													<li><a href="/search/simulation">Simulation</a>
													</li>
												</ul>
											</div>									
											<div class="col-sm-3">
												<ul>
													<li><a href="/search/sports">Sports</a>
													</li>
													<li><a href="/search/strategy">Strategy</a>
													</li>
													<li><a href="/search/trivia">Trivia</a>
													</li>
													<li><a href="/search/word">Word</a>
													</li>
												</ul>
											</div>	
										</div>
									</div>
								</li>
							</ul>
						</li>
						<li class="dropdown use-yamm yamm-fw">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">Console games <b class="caret"></b></a>
							<ul class="dropdown-menu">
								<li>
									<div class="yamm-content">
										<div class="row">
											<div class="col-sm-3">
												<ul>
													<li><a href="/search/action">Action</a>
													</li>
													<li><a href="/search/adventure">Adventure</a>
													</li>
													<li><a href="/search/arcade">Arcade</a>
													</li>
													<li><a href="/search/board">Board</a>
													</li>
												</ul>
											</div>
											<div class="col-sm-3">
												<ul>
													<li><a href="/search/card">Card</a>
													</li>
													<li><a href="/search/casino">Casino</a>
													</li>
													<li><a href="/search/family">Family</a>
													</li>
													<li><a href="/search/music">Music</a>
													</li>
												</ul>
											</div>
											<div class="col-sm-3">
												<ul>
													<li><a href="/search/puzzle">Puzzle</a>
													</li>
													<li><a href="/search/racing">Racing</a>
													</li>
													<li><a href="/search/rpg">RPG</a>
													</li>
													<li><a href="/search/simulation">Simulation</a>
													</li>
												</ul>
											</div>									
											<div class="col-sm-3">
												<ul>
													<li><a href="/search/sports">Sports</a>
													</li>
													<li><a href="/search/strategy">Strategy</a>
													</li>
													<li><a href="/search/trivia">Trivia</a>
													</li>
													<li><a href="/search/word">Word</a>
													</li>
												</ul>
											</div>	
										</div>
									</div>
								</li>
							</ul>
						</li>
					</ul>
				</div>
				<!--/.nav-collapse -->

				<div class="collapse clearfix" id="search">

					<form class="navbar-form" role="search">
						<div class="input-group">
							<input type="text" class="form-control" placeholder="Search">
							<span class="input-group-btn">

								<button type="submit" class="btn btn-template-main"><i class="fa fa-search"></i></button>

							</span>
						</div>
					</form>

				</div>
				<!--/.nav-collapse -->

			</div>


		</div>
		<!-- /#navbar -->

	</div>

	<!-- *** NAVBAR END *** -->

</header>

<!-- *** LOGIN MODAL ***
_________________________________________________________ -->
<div class="modal fade" id="login-modal" tabindex="-1" role="dialog" aria-labelledby="Login" aria-hidden="true">
	<div class="modal-dialog modal-sm">

		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h4 class="modal-title" id="Login">Customer login</h4>
			</div>
			<div class="modal-body">
				<form method="post">
					<div class="form-group">
						<input type="text" class="form-control" id="email_modal" placeholder="email">
					</div>
					<div class="form-group">
						<input type="password" class="form-control" id="password_modal" placeholder="password">
					</div>

					<p class="text-center">
						<button class="btn btn-template-main"><i class="fa fa-sign-in"></i> Log in</button>
					</p>

				</form>

				<p class="text-center text-muted">Not registered yet?</p>
				<p class="text-center text-muted"><a href="customer-register.html"><strong>Register now</strong></a>! It is easy and done in 1&nbsp;minute and gives you access to special discounts and much more!</p>

			</div>
		</div>
	</div>
</div>

<!-- *** LOGIN MODAL END *** -->

{% block content %}		
{% endblock content %}

<!-- *** COPYRIGHT ***
_________________________________________________________ -->

<div id="copyright">
	<div class="container">
		<div class="col-md-12">
			<p class="pull-left">&copy; 2017. Thang Le, Huy Nguyen.</p>
			<p class="pull-right">Template by <a href="https://bootstrapious.com/free-templates">Bootstrapious</a> 
				<!-- Not removing these links is part of the license conditions of the template. Thanks for understanding :) If you want to use the template without the attribution links, you can do so after supporting further themes development at https://bootstrapious.com/donate  -->
				<br>
				Games taken from <a href="http://www.giantbomb.com/api/">Giantbomb</a>
			</p>
		</div>
	</div>
</div>
<!-- /#copyright -->

<!-- *** COPYRIGHT END *** -->
</div>
<!-- /#all -->

<!-- #### JAVASCRIPT FILES ### -->

<script src="{% static 'jquery/dist/jquery.min.js' %}" type="text/javascript"></script>
<script src="{% static 'bootstrap/dist/js/bootstrap.min.js' %}" type="text/javascript"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.min.js" type="text/javascript"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/waypoints/4.0.1/jquery.waypoints.min.js" type="text/javascript"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Counter-Up/1.0.0/jquery.counterup.min.js" type="text/javascript"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-parallax/1.1.3/jquery-parallax-min.js" type="text/javascript"></script>
<script src="{% static 'gamesearch/js/front.js' %}" type="text/javascript"></script>

<!-- owl carousel -->
<script src="{% static 'owl.carousel/dist/owl.carousel.js' %}" type="text/javascript"></script>

<!-- make columns have same height -->
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery.matchHeight/0.7.0/jquery.matchHeight-min.js" type="text/javascript"></script>

<script src="{% static 'gamesearch/js/raty/lib/jquery.raty.js' %}" type="text/javascript"></script>

<script type="text/javascript" src="{% static 'gamesearch/js/main.js' %}"></script>
<script src="{% static 'gamesearch/js/custom.js'%}" type="text/javascript"></script>
</body>
</html>

gamesearch/templates/gamesearch/game.html
{% extends "gamesearch/base.html" %}
{% block content %}
<section>
	<div class="page-header text-center">
		<h1>{{ game.name }}</h1>
	</div>
	<div class="container-fluid lead">
		<div class="row" style="margin-bottom: 30px">
			<div class="col-md-12 text-center">
				<img src="{{ game.cover_img }}" alt="">
			</div>
		</div>
		<div class="row text-center">
			<p><strong>Genres: </strong>{{ genres }}</p>
		</div>
		<div class="row">
			<div class="col-md-12 giantbomb-data">
				{{ game.description | safe }}
			</div>
		</div>
		<div class="row">
			<div class="col-md-12">
				<h3>Rate this game:</h3>
				<div class="rating rating-modify"></div>
			</div>
		</div>
	</div>
</section>
{% endblock content %}

gamesearch/templates/gamesearch/index.html
{% extends "gamesearch/base.html" %}
{% load staticfiles %}
{% block content %}
<section>
	<div class="home-carousel">
		<div class="container-fluid">
			<div class="row">
				<div class="col-md-12">
					<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
						<ol class="carousel-indicators">
							<li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
							<li data-target="#carousel-example-generic" data-slide-to="1"></li>
							<li data-target="#carousel-example-generic" data-slide-to="2"></li>
						</ol>
						<div class="carousel-inner">
							<div class="item">
								<img class="slide-image" src="http://i.imgur.com/9RZJD1k.png" alt="">
							</div>
							<div class="item active">
								<img class="slide-image" src="https://images4.alphacoders.com/208/thumb-1920-208896.jpg" alt="">
							</div>
							<div class="item">
								<img class="slide-image" src="http://media.blizzard.com/sc2/media/wallpapers/wall005/wall005-1920x1080.jpg" alt="">
							</div>
						</div>
						<a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
							<span class="glyphicon glyphicon-chevron-left"></span>
						</a>
						<a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
							<span class="glyphicon glyphicon-chevron-right"></span>
						</a>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

<section class="bar background-white no-mb">
	<div class="container-fluid">
		<div class="row">
			<div class="col-md-12">
				{% if games %}
					<div class="heading text-center">
						<h2>Your search results</h2>
					</div>
					<p class="lead text-center">These are what we have found so far. Enjoy the games!</p>
				{% else %}
					<p class="lead text-center">Type what you want to search in the searchbox above!</p>
				{% endif %}
			</div>
		</div>
		<div class="row">
			{% for g in games %}
				<div class="col-md-3 col-sm-6">
					<div class="box-image-text blog">
						<div class="top fix-height">
							<div class="image">
								{% if g.image.super_url %}
								<img src="{{ g.image.super_url }}" alt="" class="img-responsive"></a>
								{% else %}
								<img src="{% static 'gamesearch/images/No_Cover.jpg' %}" alt="" class="img-responsive">
								{% endif %}
							</div>
							<div class="bg"></div>
						</div>
						<div class="content">
							<div class="rating" data-id="{{ g.id }}"></div>
							<h4><a href="{% url 'gamesearch:game' g.id %}">{{ g.name }}</a></h4>
							<p class="intro">{{ g.deck }}</p>
						</div>
					</div>
				</div>
			{% endfor %}          
		</div>
	</div>
</section>
{% endblock %}

gamesearch/templates/gamesearch/topgames.html
{% extends "gamesearch/base.html" %}
{% load staticfiles %}
{% block content %}
<title>Top Action Games </title>
<section>
	<div class="container-fluid">
		<!-- HEADER -->
		<div class="row">
			<div class="col-md-12">
				<div class="heading text-center">
					<h1>Top Action Games</h1>
				</div>
			</div>
		</div>

		<!-- LIST GAMES -->
		<ol class="list-unstyled">
			<li>
				<h2>Dota 2 (4.9/5)</h2>
				<div class="row">
					<div class="col-md-4 col-xs-12">
						<img class="img-responsive" src="https://images4.alphacoders.com/208/thumb-1920-208896.jpg">
					</div>
					<div class="col-md-8 col-xs-12">
						<p>Dota 2 is a free-to-play multiplayer online battle arena (MOBA) video game developed and published by Valve Corporation. The game is the stand-alone sequel to Defense of the Ancients (DotA), which was a community-created mod for Blizzard Entertainment's Warcraft III: Reign of Chaos and its expansion pack, The Frozen Throne</p>
					</div>
				</div>
				<hr>
			</li>

			<li>
				<h2>Dota 2 (4.9/5)</h2>
				<div class="row">
					<div class="col-md-4 col-xs-12">
						<img class="img-responsive" src="https://images4.alphacoders.com/208/thumb-1920-208896.jpg">
					</div>
					<div class="col-md-8 col-xs-12">
						<p>Dota 2 is a free-to-play multiplayer online battle arena (MOBA) video game developed and published by Valve Corporation. The game is the stand-alone sequel to Defense of the Ancients (DotA), which was a community-created mod for Blizzard Entertainment's Warcraft III: Reign of Chaos and its expansion pack, The Frozen Throne</p>
					</div>
				</div>
				<hr>
			</li>

			<li>
				<h2>Dota 2 (4.9/5)</h2>
				<div class="row">
					<div class="col-md-4 col-xs-12">
						<img class="img-responsive" src="https://images4.alphacoders.com/208/thumb-1920-208896.jpg">
					</div>
					<div class="col-md-8 col-xs-12">
						<p>Dota 2 is a free-to-play multiplayer online battle arena (MOBA) video game developed and published by Valve Corporation. The game is the stand-alone sequel to Defense of the Ancients (DotA), which was a community-created mod for Blizzard Entertainment's Warcraft III: Reign of Chaos and its expansion pack, The Frozen Throne</p>
					</div>
				</div>
				<hr>
			</li>
		</ol>
	</div>
</section>
{% endblock %}

homepage/templates/homepage/index.html
<!DOCTYPE html>
<html>
<head>
	<title>Home</title>
	{% load staticfiles %}
	<!--     <link rel="stylesheet" href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}"> -->
	<link rel="stylesheet" href="{% static 'homepage/css/main.css'%}" />
</head>
<body class="loading">
	<div id="wrapper">
		<div id="bg"></div>
		<div id="overlay"></div>
		<div id="main">

			<!-- Header -->
			<header id="header">
				<h1>Google for Gamer</h1>
				<p>Your database for games</p>
				<nav>
					<ul>
					<li><a href="/search" class="icon fa-search"><span class="label">Search</span></a></li>
								<!-- <li><a href="#" class="icon fa-facebook"><span class="label">Facebook</span></a></li>
								<li><a href="#" class="icon fa-dribbble"><span class="label">Dribbble</span></a></li>
								<li><a href="#" class="icon fa-github"><span class="label">Github</span></a></li>
								<li><a href="#" class="icon fa-envelope-o"><span class="label">Email</span></a></li> -->
							</ul>
						</nav>
					</header>

					<!-- Footer -->
					<footer id="footer">
						<span class="copyright">&copy; Chickadee. Design: <a href="http://html5up.net">HTML5 UP</a>.</span>
					</footer>

				</div>
			</div>
			<!--[if lte IE 8]><script src="assets/js/ie/respond.min.js"></script><![endif]-->
			<script>
				window.onload = function() { document.body.className = ''; }
				window.ontouchmove = function() { return false; }
				window.onorientationchange = function() { document.body.scrollTop = 0; }
			</script>
		</body>
		</html>